### ISSUE TITLE
Ignore vendor and private folders

### ISSUE THREAD

**Issue by nelsonamaya82** [pantheon-systems/example-wordpress-composer#187]
After running composer update/install, it creates the folders `vendor` and `web/private` in the root, but they are not ignored in the `.gitignore` file, should they? I can create a PR with this fix. Should we also add the `.lando.yml` file to the ignore list?

**Comment by ataylorme** [comment]
> After running composer update/install, it creates the folders `vendor` and `web/private` in the root, but they are not ignored in the `.gitignore` file

@nelsonamaya82 maybe you have a modified `.gitignore`?

[Everything in the `web/private` directory is ignored, except `web/private/scripts`](https://github.com/pantheon-systems/example-wordpress-composer/blob/master/.gitignore#L32:L33), which is a place to add custom [Quicksilver](https://pantheon.io/docs/quicksilver/) scripts.

[The `vendor` directory is ignored](https://github.com/pantheon-systems/example-wordpress-composer/blob/master/.gitignore#L6)

`.lando.yml` isn't ignored here nor is it committed to this repository. This repository is a template and you are meant to hack on your own copy of it.

If you have a `.lando.yml` file in your project created from this template you are welcome to add it to `.gitignore` if you like.

Personally, I think you should commit it so that all devs on the project share the same local set up.

**Comment by nelsonamaya82** [comment]
Sorry @ataylorme, you're right, for some reason my `.gitignore` file is different. And thank you for your advice on committing the `.lando.yml`, definitelly will do.

Another question, I'm also seeing some files changed in the `web/wp/wp-admin` folder, should they be committed? If I'm not wrong they were updated after running composer update/install.

Thanks.

**Comment by ataylorme** [comment]
> Another question, I'm also seeing some files changed in the web/wp/wp-admin folder, should they be committed? 

No, `web/wp` should be ignored as WordPress core is installed with Composer. So the files you want to commit are `composer.json` and `composer.lock`, while keeping all the dependencies installed with Composer ignored.

I'm not sure where your project differs and what customizations you have made but you might consider copying the `.gitignore` from our example repo into your project.

**Comment by nelsonamaya82** [comment]
Thanks!
