### ISSUE TITLE
wrong install folder

### ISSUE THREAD

**Issue by nullvariable** [pantheon-systems/example-wordpress-composer#189]
All the other paths reference `web` as the root, but this installs WordPress into the `web/wp` folder.

https://github.com/pantheon-systems/example-wordpress-composer/blob/c5520c9c6ad2af5178f8f292894d283db3dae048/composer.json#L51

**Comment by ataylorme** [comment]
@nullvariable we are installing WordPress core to `web/wp` intentionally.

This is in order to faciliate WordPress core being installed as a dependency along with other packages. See [Giving WordPress Its Own Directory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/).

We have also decouple `wp-content` from WordPress core so that the themes/plugins installed with Composer do not have to be in the same directory as WordPress core. 

Essentially, we don't want to install one set of dependencies (themes/plugins) inside another dependency (WordPress core).

The [Editing `wp-config.php` article](https://wordpress.org/support/article/editing-wp-config-php/#wp_siteurl) has more details on this and we have set the required constants for this setup (`WP_HOME`, `WP_SITEURL`, `WP_CONTENT_DIR` and `WP_CONTENT_URL`) in `wp-config.php`.

**Comment by nullvariable** [comment]
thanks, I copied this for my own testing and missed that bit of logic when I reworked, so it looked broken on my end. Thanks for the detailed explanation!

**Comment by ataylorme** [comment]
👍 I'll close this out then
