### ISSUE TITLE
Stability for this package.

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/example-wordpress-composer#33]
Right now the install instructions need ` --stability=dev` inside the

```
terminus build:project:create pantheon-systems/example-wordpress-composer my-new-site --team="Agency Org Name" --stability=dev
```

`composer create-project` won't complete otherwise.

@greg-1-anderson, once @ataylorme is back, let's discuss stability markings for these packages. In the mean time, I'm updating the readme here so that people can copy/paste successfully: https://github.com/pantheon-systems/example-wordpress-composer/pull/32

**Comment by greg-1-anderson** [comment]
I think that the stability flag is only needed because we only have a 1.0.0-alpha1 tag here at the moment. Once we tag a 1.0.0 stable, this shouldn't be necessary any longer.

Since WordPress and Drupal 7 both have passing tests in the Terminus Build Tools plugin, I think we could tag a 1.0.0 release for both of these examples. Let's discuss as suggested.

**Comment by stevector** [comment]
From an internal meeting: We'll tag 1.0 as soon as the PHP version is set in composer.json. Further changes to PHP version will result in tagging 2.0, 3.0, etc.

**Comment by stevector** [comment]
During today's meeting we decided to tag 1.0.0[ during office hours](https://pantheon.io/agencies/office-hours) on Wednesday.

**Comment by stevector** [comment]
Not only did we get 1.0.0, I tagged 1.0.1 :)
